# Information 
this was code base in this [link](https://www.kaggle.com/code/satishgunjal/tutorial-k-fold-cross-validation/notebook)

from the result of google search in "DataSet TB3.xls kaggle n k-Fold Cross Validation"

# Reference
1. [Selecting the best model in scikit-learn using cross-validation](https://www.youtube.com/watch?v=6dbrR-WymjI)
2. [5 Reasons why you should use Cross-Validation in your Data Science Projects](https://towardsdatascience.com/5-reasons-why-you-should-use-cross-validation-in-your-data-science-project-8163311a1e79)

In [3]:
import pandas as pd
import warnings
import numpy as np
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn import linear_model, tree, ensemble

# retreive the data needed to be train

In [4]:
train_data = pd.read_excel('DataSetTB3_SHARE.xlsx')
train_data

,idData,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1496,9,0,0,0,0,0,0,0,0,...,253,74,0,0,0,0,0,0,0,0
1496,1497,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1497,1498,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1498,1499,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1499,1500,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Select only the numeric columns only

In [5]:
# Select numeric columns only
numeric_cols = [cname for cname in train_data.columns if train_data[cname].dtype in ['int64', 'float64']]
X = train_data[numeric_cols].copy()
y = train_data['label']

In [6]:
print("Shape of input data: {} and shape of target variable: {}".format(X.shape, y.shape))
pd.concat([X, y], axis=1).head() # Show first 5 training examples

Shape of input data: (1500, 786) and shape of target variable: (1500,)

,idData,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,label
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# train the data using k-fold
'kf'(StratiFiedKFold splitting stratergy) object as input to cross_val_score() method The folds are made by preserving the percentage of samples for each class.

In [7]:
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cnt = 1

# split()  method generate indices to split data into training and test set.

In [8]:
for train_index, test_index in kf.split(X, y):
    print(f'Fold:{cnt}, Train set: {len(train_index)}, Test set:{len(test_index)}')
    cnt+=1

Fold:1, Train set: 1350, Test set:150
Fold:2, Train set: 1350, Test set:150
Fold:3, Train set: 1350, Test set:150
Fold:4, Train set: 1350, Test set:150
Fold:5, Train set: 1350, Test set:150
Fold:6, Train set: 1350, Test set:150
Fold:7, Train set: 1350, Test set:150
Fold:8, Train set: 1350, Test set:150
Fold:9, Train set: 1350, Test set:150
Fold:10, Train set: 1350, Test set:150

# Using Logistic Regression

In [9]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    score = cross_val_score(linear_model.LogisticRegression(random_state= 42), X, y, cv= kf, scoring="accuracy")
    print(f'Scores for each fold are: {score}')
    print(f'Average score: {"{:.2f}".format(score.mean())}')

Scores for each fold are: [0.84666667 0.88666667 0.86       0.82       0.86666667 0.9
 0.86666667 0.85333333 0.86       0.83333333]
Average score: 0.86

# Using Decision Classifier

In [11]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    score = cross_val_score(tree.DecisionTreeClassifier(random_state= 42), X, y, cv= kf, scoring="accuracy")
    print(f'Scores for each fold are: {score}')
    print(f'Average score: {"{:.2f}".format(score.mean())}')

Scores for each fold are: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Average score: 1.00

# Using Random Forest Classifier

In [12]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    score = cross_val_score(ensemble.RandomForestClassifier(random_state= 42), X, y, cv= kf, scoring="accuracy")
    print(f'Scores for each fold are: {score}')
    print(f'Average score: {"{:.2f}".format(score.mean())}')

Scores for each fold are: [0.94666667 0.93333333 0.96       0.9        0.95333333 0.96
 0.92666667 0.96666667 0.92       0.9       ]
Average score: 0.94

# Logistic Classifier Tuning

In [13]:
algorithms = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

for algo in algorithms:
    score = cross_val_score(linear_model.LogisticRegression(max_iter= 4000, solver= algo, random_state= 42), X, y, cv= kf, scoring="accuracy")
    print(f'Average score({algo}): {"{:.3f}".format(score.mean())}')

Average score(newton-cg): 0.867
Average score(lbfgs): 0.859
Average score(liblinear): 0.831
Average score(sag): 0.865
Average score(saga): 0.863

# Decision Tree Classifier Tuning

In [14]:
max_depth = [1,2,3,4,5,6,7,8,9,10]

for val in max_depth:
    score = cross_val_score(tree.DecisionTreeClassifier(max_depth= val, random_state= 42), X, y, cv= kf, scoring="accuracy")
    print(f'Average score({val}): {"{:.3f}".format(score.mean())}')

Average score(1): 0.200
Average score(2): 0.300
Average score(3): 0.400
Average score(4): 0.600
Average score(5): 0.700
Average score(6): 0.800
Average score(7): 1.000
Average score(8): 1.000
Average score(9): 1.000
Average score(10): 1.000

# Random Forest Classifier Tuning

In [15]:
n_estimators = [50, 100, 150, 200, 250, 300, 350]

for val in n_estimators:
    score = cross_val_score(ensemble.RandomForestClassifier(n_estimators= val, random_state= 42), X, y, cv= kf, scoring="accuracy")
    print(f'Average score({val}): {"{:.3f}".format(score.mean())}')

Average score(50): 0.924
Average score(100): 0.937
Average score(150): 0.940
Average score(200): 0.940
Average score(250): 0.941
Average score(300): 0.942
Average score(350): 0.941